GET http://localhost:8000

###
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "Rakesh",
    "email": "admin@standardbredtrader.com.au",
    "passworkd": "XaWaJBgfb2AgoNFR"
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "admin@standardbredtrader.com.au",
    "passworkd": "XaWaJBgfb2AgoNFR"
}
